version: '2'
volumes: 
    data:
services:
  commento:
    build: .
    depends_on:
      - db
    ports:
      - "80:8080"
    environment:
     - COMMENTO_PORT=8080
     - COMMENTO_POSTGRES=postgres://commento:commento@db:5432/commento?sslmode=disable
  db:
    build: ./postgres
    expose:
      - "5432"
    volumes: 
      - 'data:/data'
    environment:
     - PGDATA=/data
     - POSTGRES_USER=commento
     - POSTGRES_PASSWORD=commento
